apiVersion: v1
kind: PersistentVolume
metadata:
  name: project2-pv2-cleifsonaraujo
  namespace: cleifsonaraujo
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: /home/cleifson/projects/playlist-recommendation-service
