apiVersion: v1
kind: PersistentVolume
metadata:
  name: project2-pv2-cleifsonaraujo
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/project2-pv2-cleifsonaraujo