apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: cleifsonaraujo
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 52011
  clusterIP: None
