apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: cleifsonaraujo
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 30502
      targetPort: 5000
  clusterIP: None
